movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('country_list/', views.CountryListView.as_view(), name='country_list'),
    path('country_detail/<int:pk>', views.CountryDetailView.as_view(), name='country_detail'),
    path('movie_list/', views.MovieListView.as_view(), name='movie_list'),  # Country View
    path('movie_detail/<int:pk>', views.MovieDetailView.as_view(), name='movie_detail'),
    path('search/', views.SearchView.as_view(), name="search"),
    path('search_result/', views.SearchResultView.as_view(), name="search_result")
]

movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movieapp/', include('movieapp.urls')),
    path('', RedirectView.as_view(url='movieapp')),
]

movieapp/models.py
import datetime

from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import (MinLengthValidator, MinValueValidator, MaxValueValidator)
from django.db import models


# Create your models here.

class Country(models.Model):
    common = models.CharField(max_length=100)
    official = models.CharField(max_length=100)
    capital = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    subregion = models.CharField(max_length=50, null=True)
    flag = models.CharField(max_length=100)
    map = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'countries'
        ordering = ['common']

    def __str__(self):
        return self.common

class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.CharField(max_length=100)
    imdbID = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    poster= models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'movies'
        ordering = ['title']

    def __str__(self):
        return self.title

movieapp/views.py
import urllib.parse
from urllib.request import urlopen
import json

from django.core import paginator
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.conf import settings
from django.core.paginator import Paginator
from .models import *



class HomeView(TemplateView):
    template_name = 'movieapp/index.html'


class SearchView(TemplateView):
    template_name = 'movieapp/search.html'

class SearchResultView(ListView):
    model = Country
    template_name = 'movieapp/search_result.html'
    table = None



    def get_queryset(self):
        object_list = []
        query = self.request.GET.get('q')
        self.table = self.request.GET.get('table')
        if self.table == 'country':
            object_list = Country.objects.filter(common__icontains=query)
        elif self.table == 'movie':
            value = urllib.parse.quote_plus(query)
            search = 's=' + value
            result = '&'.join([settings.OMDB_URL, search])
            print(result)
            response = urlopen(result)
            data = json.loads(response.read())
            if data['Response'] == 'True':
                for obj in data['Search']:
                    object_list.append(obj)
                    Movie.objects.get_or_create(title=obj['Title'], year=obj['Year'], imdbID=obj['imdbID'],
                                                type=obj['Type'], poster=obj['Poster'])

        return object_list


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['table'] = self.table
        return context


class CountryListView(ListView):
    template_name = 'movieapp/country_list.html'
    model = Country
    context_object_name = 'countries'
    paginate_by = 10
    ordering = ['common']
    countries = Country.objects.order_by('id')



class CountryDetailView(DetailView):
    model = Country

class MovieListView(ListView):
    model = Movie
    queryset = Movie.objects.order_by('title')
    context_object_name = 'movies'
    paginate_by = 10
    ordering = ['title']

class MovieDetailView(DetailView):
    model = Movie

movieapp/templates/movieapp/country_detail.html
{% extends 'base.html' %}
{% block content %}
	<div class="row">
        <div class="col-8 mt-2 mx-auto">
            <h3>Country Details</h3>
                <table class="table table-bordered">
                    <td><h2><strong>{{ country.common }}</strong></h2>
                        <table class="table table-bordered">
                            <tr>
                            <td><strong>Common name</strong></td>
                            <td>{{ country.common }}</td>
                            </tr>
                            <tr>
                    <td><strong>Official name</strong></td>
                    <td>{{ country.official }}</td>
                </tr>
                <tr>
                    <td><strong>Capital</strong></td>
                    <td>{{ country.capital }}</td>
                </tr>
                <tr>
                    <td><strong>Region</strong></td>
                    <td>{{ country.region }}</td>
                </tr>
                <tr>
                    <td><strong>Subregion</strong></td>
                    <td>{{ country.subregion }}</td>
                </tr>
                <tr>
                    <td><strong>Flag</strong></td>
                    <td><a href="{{ country.flag }}" target="_blank"><img src="{{ country.flag }}" alt="Flag" style="width: 100px;"></a></td>
                </tr>
                <tr>
                    <td><strong>Map</strong></td>
                    <td><a href="{{ country.map }}" target="_blank">Google Maps</a></td>
                </tr>
                    </td>
            </table>
            <p class="text-end">
                <a href="{% url 'movieapp:country_list' %}">List of countries</a>
            </p>
        </div>
    </div>
{% endblock %}

movieapp/templates/movieapp/country_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 mx-auto">
                <h3>List of countries</h3>
                            <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        </li>
                    {% endif %}

                    <li class="page-link text-dark">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr class="text-center">
                            <th>#</th>
                            <th>Country</th>
                        </tr>
                    </thead>
                    <tbody>
{% for country in countries %}
    <tr>
        <td style="text-align: right", width="20">{{ page_obj.start_index|add:forloop.counter0 }}</td>
        <td><a href="{% url 'movieapp:country_detail' country.id %}">{{ country.common }}</a></td>
    </tr>
{% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

movieapp/templates/movieapp/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>Movie staff</h2>
{% endblock %}

movieapp/templates/movieapp/movie_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-8 mt-2 mx-auto">
            <h3>Movie Details</h3>
            <table class="table table-bordered">
                <td>
                    <h2><strong>{{ movie.title }}</strong></h2>
                    <table class="table table-bordered">
                        <tr>
                            <td><strong>Title</strong></td>
                            <td>{{ movie.title }}</td>
                        </tr>
                        <tr>
                            <td><strong>Year</strong></td>
                            <td>{{ movie.year }}</td>
                        </tr>
                        <tr>
                            <td><strong>IMDB</strong></td>
                            <td><a href="https://omdbapi.com/?apikey=599afc0&i={{ movie.imdbID }}" target="_blank">IMDB</a></td>
                        </tr>
                        <tr>
                            <td><strong>Type</strong></td>
                            <td>{{ movie.type }}</td>
                        </tr>
                        {% if movie.poster != "N/A" %}
                        <tr>
                            <td><strong>Poster</strong></td>
                            <td>
                                <a href="{{ movie.poster }}" target="_blank">
                                    <img src="{{ movie.poster }}" alt="Poster" style="width: 100px;">
                                </a>
                            </td>
                        </tr>
                        {% endif %}
                    </table>
                </td>
            </table>
            <p class="text-end">
                <a href="{% url 'movieapp:movie_list' %}">List of movies</a>
            </p>
        </div>
    </div>
{% endblock %}

movieapp/templates/movieapp/movie_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <h3>Movies list</h3>
                            <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        </li>
                    {% endif %}

                    <li class="page-link text-dark">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr class="text-center">
                            <th>#</th>
                            <th>Title</th>
                        </tr>
                    </thead>
                    {% for movie in movies %}
                        <tr>
                            <td style="text-align: right", width="20">{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td><a href="{% url 'movieapp:movie_detail' pk=movie.id %}">{{ movie.title }}</a></td>
                        </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

movieapp/templates/movieapp/search.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'movieapp:search_result' %}" method="get">
        <div class="row">
            <div class="col-8 mx-auto">
                <div class="row">
                    <h3>Search</h3>
                    <div class="col-4">
                        <input type="text" name ="q" id="q" placeholder="Search phrase" class="form-control">
                    </div>

                    <div class="col-4">
                        <select name="table" class="form-select form-control">
                            <option value="country" selected>Countries</option>
                            <option value="movie">Movies</option>
                        </select>
                    </div>

                    <div class="col-auto">
                        <input type="submit" value="Search" class="btn btn-primary form-control">
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

movieapp/templates/movieapp/search_result.html
{% extends 'base.html' %}
{% block content %}
	<div class="row">
        <div class="col-8 mx-auto">
            <div class="row">
                <h3>Search Results</h3>
                {% if object_list and table == 'country' %}
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr class="text-center">
                            <th>Common name</th>
                            <th>Official name</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for country in object_list %}
                            <tr>
                                <td>{{ country.common }}</td>
                                <td>{{ country.official }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% elif table == 'movie' %}
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr class="text">
                            <th>Title</th>
                            <th>Year</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for movie in object_list %}
                            <tr>
                                <td>{{ movie.Title }}</td>
                                <td>{{ movie.Year }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                        <p class="text-danger">No result found</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MovieApp</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </head>
    <body>
        {% include 'menu.html' %}
        <div class="container">
            {% block content %}

            {% endblock %}
        </div>
    </body>
</html>

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'movieapp:index' %}">MovieApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'movieapp:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movieapp:search' %}">Search</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Lists
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'movieapp:country_list' %}">Countries</a></li>
            <li><a class="dropdown-item" href="{% url 'movieapp:movie_list' %}">Movies</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>